-- V129: Create school_leave_applications table
CREATE TABLE school_leave_applications (
    id               BIGINT UNSIGNED  AUTO_INCREMENT PRIMARY KEY,
    school_id        BIGINT UNSIGNED  NOT NULL,
    academic_year_id BIGINT UNSIGNED  NOT NULL,
    applicant_type   VARCHAR(10)      NOT NULL,
    student_id       BIGINT UNSIGNED  NULL,
    teacher_id       BIGINT UNSIGNED  NULL,
    leave_type       VARCHAR(20)      NOT NULL,
    start_date       DATE             NOT NULL,
    end_date         DATE             NOT NULL,
    total_days       INT              NOT NULL,
    working_days     INT              NULL,
    reason           VARCHAR(1000)    NOT NULL,
    evidence_file_id BIGINT UNSIGNED  NULL,
    status           VARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    approved_by_id   BIGINT UNSIGNED  NULL,
    approved_at      DATETIME         NULL,
    rejection_reason VARCHAR(1000)    NULL,
    revoked_by_id    BIGINT UNSIGNED  NULL,
    revoked_at       DATETIME         NULL,
    created_at       DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by       BIGINT UNSIGNED  NULL,
    updated_by       BIGINT UNSIGNED  NULL,

    CONSTRAINT fk_leave_school   FOREIGN KEY (school_id)        REFERENCES school_schools(id),
    CONSTRAINT fk_leave_year     FOREIGN KEY (academic_year_id) REFERENCES school_academic_years(id),
    CONSTRAINT fk_leave_student  FOREIGN KEY (student_id)       REFERENCES school_students(id),
    CONSTRAINT fk_leave_teacher  FOREIGN KEY (teacher_id)       REFERENCES school_teachers(id),
    INDEX idx_leave_school  (school_id),
    INDEX idx_leave_student (student_id),
    INDEX idx_leave_teacher (teacher_id),
    INDEX idx_leave_status  (status),
    INDEX idx_leave_dates   (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
